nacos:
  host: "http://nacos:8848"
  console_port: 8080  # v3 必需，v2 可忽略
  username: "nacos"
  password: "nacos"

backup:
  output_dir: "/app/backups"
  upload_to_minio: true
  auto_clean_days: 1
  minio:
    endpoint: "http://minio:9000"  
    access_key: "admin"
    secret_key: "Minio@123.com"
    bucket: "nacos-backups"
    secure: false

logging:
  level: INFO
  file: "/app/logs/backup.log"

schedule:
  enabled: true
  cron: "@hourly"  # 可选值："@hourly", "03:00", "15:30", "@daily", "@weekly"


health-check:
  port: 8080

timezone: "Asia/Shanghai"