name: Build and Deploy Nacos Backup Image

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '0 2 1 * *' # 每月1号凌晨2点

jobs:
  build:
    name: Build and Push Multi-Arch Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nacos-backup:latest
          platforms: linux/amd64,linux/arm64