name: Build and Deploy Nacos Backup Image

on:
  push:
    branches:
      - main  # 当 main 分支有提交时触发
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '0 2 1 * *' # 每月1号凌晨2点

name: 'Custom Build and Push'
description: 'Build and Push Docker Image'
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup QEMU
      uses: docker/setup-qemu@v2

    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ inputs.tags }}
        platforms: ${{ inputs.platforms }}